//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Demo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent_Table
    {
        public int id { get; set; }
        public string Agent_Name { get; set; }
        public string Specialization { get; set; }
        public string Service_Type { get; set; }
        public Nullable<double> Service_Charge { get; set; }
        public string Gender { get; set; }
        public string Agent_Type { get; set; }
        public string Address { get; set; }
        public string Mobile_Number { get; set; }
        public Nullable<double> Share_Charge { get; set; }
        public Nullable<double> Basic_Salary { get; set; }
    }
}
