//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Demo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id { get; set; }
        public string name { get; set; }
        public string father_name { get; set; }
        public string village { get; set; }
        public string post { get; set; }
        public string thana { get; set; }
        public string district { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string reference { get; set; }
        public string nid { get; set; }
        public double discount_percentage { get; set; }
        public string image { get; set; }
    }
}
