//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Demo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument_Table
    {
        public int id { get; set; }
        public string Instrument_Name { get; set; }
        public string Instrument_Service { get; set; }
        public string Instrument_Number { get; set; }
        public string Instrument_Status { get; set; }
        public string Instrument_Assignee { get; set; }
    }
}
