//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Demo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSrvcAgntMapDettail
    {
        public int id { get; set; }
        public Nullable<int> TableSrvcMapID { get; set; }
        public Nullable<int> SrvcTypeID { get; set; }
        public Nullable<int> Service { get; set; }
    }
}
