//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Demo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token_Dettails_Table
    {
        public int id { get; set; }
        public Nullable<int> Token_ID { get; set; }
        public Nullable<int> Service_Number { get; set; }
        public Nullable<int> Agent_Number { get; set; }
    }
}
