//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Demo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token_Table
    {
        public int id { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Contact_Number { get; set; }
        public Nullable<int> Customer_Number { get; set; }
        public Nullable<double> Service_Charge { get; set; }
        public Nullable<double> Discount_ServiceCharge { get; set; }
        public Nullable<double> NetTotal { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Service_Type_ID { get; set; }
    }
}
